DROP TABLE IF EXISTS statistics CASCADE;

CREATE TABLE IF NOT EXISTS statistics
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       VARCHAR(100)                            NOT NULL,
    uri       VARCHAR(255)                            NOT NULL,
    ip        VARCHAR(15)                             NOT NULL,
    timestamp TIMESTAMP                               NOT NULL,
    PRIMARY KEY (id)
);